# Generated by Django 4.2.6 on 2023-10-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_projects', '0001_initial'),
        ('employee_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Prefer not to say', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='org_projects.projects'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_mng.designation'),
        ),
    ]
