# Generated by Django 4.2.6 on 2023-10-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designations', '0001_initial'),
        ('employee_mng', '0003_remove_designation_designation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='designations.designation'),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
