# Generated by Django 4.2.6 on 2023-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mng', '0004_alter_employee_designation_delete_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_department',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_project',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
