# Generated by Django 4.2.6 on 2023-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mng', '0007_alter_employee_current_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_department',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_project',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
