# Generated by Django 4.2.6 on 2023-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mng', '0009_alter_employee_assigned_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_role',
            field=models.CharField(blank=True, default='employee', max_length=100),
        ),
    ]
