# Generated by Django 4.2.6 on 2023-10-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_mng', '0001_initial'),
        ('department_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department_mng.department')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_mng.employee')),
            ],
        ),
    ]
