# Generated by Django 4.2.6 on 2023-10-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mng', '0005_alter_employee_current_department_and_more'),
        ('department_mng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dep_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee_mng.employee'),
        ),
    ]
