# Generated by Django 4.2.6 on 2023-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_projects', '0002_remove_projects_project_id_projects_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
