# Generated by Django 4.2.6 on 2023-10-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mng', '0010_alter_employee_assigned_role'),
        ('org_projects', '0003_alter_projects_description_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee_mng.employee'),
        ),
    ]
